apiVersion: v1
items:

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: gitness
    name: gitness
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: gitness
    template:
      metadata:
        labels:
          app: gitness
      spec:
        containers:
        - image: gcr.io/XXXXX-XXXXXXX/gitness
          imagePullPolicy: Never
          name: gitness
      
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: gitness
    name: gitness
  spec:
    ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      app: gitness

- apiVersion: networking.k8s.io/v1beta1
  kind: Ingress
  metadata:
    name: gitness
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      kubernetes.io/ingress.class: "nginx"
  spec:
    rules:
    - http:
        paths:
        - path: /pm/(.*)
          backend:
            serviceName: gitness
            servicePort: 3000

kind: List
metadata:
  resourceVersion: ""
  selfLink: ""