apiVersion: v1
items:

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: scm-app
    name: scm-app
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: scm-app
    template:
      metadata:
        labels:
          app: scm-app
      spec:
        containers:
        - image: gcr.io/XXXXX-XXXXXXX/scm-app
          imagePullPolicy: Never
          name: scm-app
      
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: scm-app
    name: scm-app
  spec:
    ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      app: scm-app

- apiVersion: networking.k8s.io/v1beta1
  kind: Ingress
  metadata:
    name: scm-app
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      kubernetes.io/ingress.class: "nginx"
  spec:
    rules:
    - http:
        paths:
        - path: /pm/(.*)
          backend:
            serviceName: scm-app
            servicePort: 3000

kind: List
metadata:
  resourceVersion: ""
  selfLink: ""