version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: gitness
      POSTGRES_USER: gitness
      POSTGRES_PASSWORD: gitness
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - gitness_data:/var/lib/postgresql/data

  migration:
    build:
      context: ../db
      dockerfile: ./Dockerfile
    environment:
      DATABASE_URL: postgres://gitness:gitness@db:5432/gitness?sslmode=disable
    depends_on:
      - db

  redis:
    image: redis:6.0
    container_name: cache
    ports:
      - "6379:6379"
    expose:
      - 6379

volumes:
  gitness_data:
    driver: local